version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SqlServer2017!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - ~/.docker/sqlserver/tarefasapi/data:/var/opt/mssql/data